export const API_URL = '/get-asi-data/asiAPI'
export const HOTEL_API_URL = '/get-hotel-data'
export const HOTEL_API_KEY = 'JN9aWyj7hJ1ZrExC7Ozo'
export const ACT_API_URL = '/get-activity-data'
export const SOCIAL_API_URL = '/social'
export const URLKEY = 'd69a91d6cd9b863d161c179497de6486'
//export const API_CART_URL = 'get-cart'
//export const API_CART_URL = process.env.NODE_ENV === 'production' ? 'https://secure.yatra.com/cartservice/services' : 'get-cart'
export const API_CART_URL = process.env.NODE_ENV === 'production' ? 'https://www.yatra.com/cartservice/services' : 'get-cart'