export const GET_SEARCH_PARAMS = 'rental/GET_SEARCH_PARAMS'
export const GET_CAB_FARE_DETAILS = 'rental/GET_CAB_FARE_DETAILS'
export const GET_CABS_SRP_DATA = 'rental/GET_CABS_SRP_DATA'
export const GET_SRP_FILTER_OPTIONS = 'rental/GET_SRP_FILTER_OPTIONS'
export const GET_USER_INFO = 'rental/GET_USER_INFO'
export const GET_PROMOCODE = 'rental/GET_PROMOCODE'
export const GET_GST_DETAILS = 'rental/GET_GST_DETAILS'
export const SET_APPLY_FILTER = 'rental/SET_APPLY_FILTER'
export const SET_CAB_FARE_DETAILS = 'rental/SET_CAB_FARE_DETAILS'
export const SET_SEARCH_PARAMS = 'rental/SET_SEARCH_PARAMS'
export const SET_CABS_SRP_DATA = 'rental/SET_CABS_SRP_DATA'
export const SET_GST_FORM_DEATILS = 'rental/SET_GST_FORM_DEATILS'
export const SET_USER_INFO = 'rental/SET_USER_INFO'
export const SET_PRICE_AFTER_PROMO = 'rental/SET_PRICE_AFTER_PROMO'
export const SET_PROMO_CODE = 'rental/SET_SET_PROMO_CODE'
export const SET_P2P_SEARCH_PARAMS = 'p2p/SET_P2P_SEARCH_PARAMS'
export const GET_P2P_SEARCH_PARAMS = 'p2p/GET_P2P_SEARCH_PARAMS'

